apiVersion: containerservice.azure.com/v1api20240402preview
kind: ManagedCluster
metadata:
  name: cluster
spec:
  networkProfile:
    subnetReference: 
      armId: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/aks-dev-rg/providers/Microsoft.Network/virtualNetworks/aks-dev-vnet/subnets/aks-dev-subnet
    serviceCidr: 10.41.0.0/16
    dnsServiceIP: 10.41.0.10
    podCidr: 10.244.0.0/16
  
  identity:
    type: UserAssigned
    userAssignedIdentities:
    - reference:
        armId: /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/aks-dev-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-dev-identity
  
  aadProfile:
    adminGroupObjectIDs:
    - "00000000-0000-0000-0000-000000000000"
  
  agentPoolProfiles:
  - name: sysnpl1
    vmSize: Standard_D2s_v3
  
  nodeResourceGroup: MC_aks-dev-rg_aks-dev_eastus
  
  tags:
    environment: dev
    project: aks-project
    costCenter: it-dept
    securityLevel: standard
    managedBy: aso