apiVersion: kubernetesconfiguration.azure.com/v1api20230501
kind: Extension
metadata:
  name: aso-flux-extension
  namespace: default
spec:
  autoUpgradeMinorVersion: true
  extensionType: microsoft.flux
  identity:
    type: SystemAssigned
  owner:
    group: containerservice.azure.com
    kind: ManagedCluster
    name: aks-secure
  scope:
    cluster:
      releaseNamespace: flux-system
  configurationSettings:
    multiTenancy.enforce: "false"
    image-automation-controller.enabled: "true"
    image-reflector-controller.enabled: "true"
