# External Secrets Operator ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: eso-identity-cm
  namespace: default
data:
  # Get values with: az identity show --name eso-identity --resource-group aso-sample-rg --query '{clientId:clientId,principalId:principalId,tenantId:tenantId}' -o json
  clientId: ""  # <-- Fill this
  principalId: ""  # <-- Fill this
  tenantId: ""  # <-- Fill this
---
# External DNS ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-dns-identity-cm
  namespace: default
data:
  # Get values with: az identity show --name external-dns-identity --resource-group aso-sample-rg --query '{clientId:clientId,principalId:principalId,tenantId:tenantId}' -o json
  clientId: ""  # <-- Fill this
  principalId: ""  # <-- Fill this
  tenantId: ""  # <-- Fill this
---
# Cert Manager ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-identity-cm
  namespace: default
data:
  # Get values with: az identity show --name cert-manager-identity --resource-group aso-sample-rg --query '{clientId:clientId,principalId:principalId,tenantId:tenantId}' -o json
  clientId: ""  # <-- Fill this
  principalId: ""  # <-- Fill this
  tenantId: ""  # <-- Fill this 