# External Secrets Operator Federated Credential
apiVersion: managedidentity.azure.com/v1api20230131
kind: FederatedIdentityCredential
metadata:
  name: eso-fic
  namespace: default
spec:
  owner:
    name: eso-identity
  audiences:
    - api://AzureADTokenExchange
  issuer: https://oidc.prod-aks.azure.com/00000000-0000-0000-0000-00000000000/  # Update this with your cluster's OIDC URL
  subject: system:serviceaccount:external-secrets:external-secrets
---
# External DNS Federated Credential
apiVersion: managedidentity.azure.com/v1api20230131
kind: FederatedIdentityCredential
metadata:
  name: external-dns-fic
  namespace: default
spec:
  owner:
    name: external-dns-identity
  audiences:
    - api://AzureADTokenExchange
  issuer: https://oidc.prod-aks.azure.com/00000000-0000-0000-0000-00000000000/  # Update this with your cluster's OIDC URL
  subject: system:serviceaccount:external-dns:external-dns
---
# Cert Manager Federated Credential
apiVersion: managedidentity.azure.com/v1api20230131
kind: FederatedIdentityCredential
metadata:
  name: cert-manager-fic
  namespace: default
spec:
  owner:
    name: cert-manager-identity
  audiences:
    - api://AzureADTokenExchange
  issuer: https://oidc.prod-aks.azure.com/00000000-0000-0000-0000-00000000000/  # Update this with your cluster's OIDC URL
  subject: system:serviceaccount:cert-manager:cert-manager