# External Secrets Operator Identity
apiVersion: managedidentity.azure.com/v1api20230131
kind: UserAssignedIdentity
metadata:
  name: eso-identity
  namespace: default
spec:
  location: westcentralus
  owner:
    name: aso-sample-rg
  operatorSpec:
    configMaps:
      clientId:
        name: eso-identity-cm
        key: clientId
      principalId:
        name: eso-identity-cm
        key: principalId
      tenantId:
        name: eso-identity-cm
        key: tenantId
---
# External DNS Identity
apiVersion: managedidentity.azure.com/v1api20230131
kind: UserAssignedIdentity
metadata:
  name: external-dns-identity
  namespace: default
spec:
  location: westcentralus
  owner:
    name: aso-sample-rg
  operatorSpec:
    configMaps:
      clientId:
        name: external-dns-identity-cm
        key: clientId
      principalId:
        name: external-dns-identity-cm
        key: principalId
      tenantId:
        name: external-dns-identity-cm
        key: tenantId
---
# Cert Manager Identity
apiVersion: managedidentity.azure.com/v1api20230131
kind: UserAssignedIdentity
metadata:
  name: cert-manager-identity
  namespace: default
spec:
  location: westcentralus
  owner:
    name: aso-sample-rg
  operatorSpec:
    configMaps:
      clientId:
        name: cert-manager-identity-cm
        key: clientId
      principalId:
        name: cert-manager-identity-cm
        key: principalId
      tenantId:
        name: cert-manager-identity-cm
        key: tenantId