apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: flux-environments

resources:
  - ../clusters/dev-cluster.yaml
  - ../clusters/ppe-cluster.yaml
  - ../clusters/prd-cluster.yaml

commonLabels:
  app.kubernetes.io/name: flux-gitops
  app.kubernetes.io/part-of: aso-platform
  managed-by: flux