apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: aso-flux-dev
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/davidmarkgardiner/aso-flux
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aso-dev-cluster
  namespace: flux-system
spec:
  interval: 10m
  path: "./overlays/dev"
  prune: true
  sourceRef:
    kind: GitRepository
    name: aso-flux-dev
  validation: client
  healthChecks:
    - apiVersion: containerservice.azure.com/v1api20240402preview
      kind: ManagedCluster
      name: dev-aso-cluster
      namespace: default
  timeout: 15m
  retryInterval: 2m