apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: aso-flux-ppe
  namespace: flux-system
spec:
  interval: 5m
  ref:
    branch: main
  url: https://github.com/davidmarkgardiner/aso-flux
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aso-ppe-cluster
  namespace: flux-system
spec:
  interval: 15m
  path: "./overlays/ppe"
  prune: true
  sourceRef:
    kind: GitRepository
    name: aso-flux-ppe
  validation: client
  healthChecks:
    - apiVersion: containerservice.azure.com/v1api20240402preview
      kind: ManagedCluster
      name: ppe-aso-cluster
      namespace: default
  timeout: 20m
  retryInterval: 3m