apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: aso-flux-prd
  namespace: flux-system
spec:
  interval: 10m
  ref:
    branch: main
  url: https://github.com/davidmarkgardiner/aso-flux
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: aso-prd-cluster
  namespace: flux-system
spec:
  interval: 30m
  path: "./overlays/prd"
  prune: true
  sourceRef:
    kind: GitRepository
    name: aso-flux-prd
  validation: client
  healthChecks:
    - apiVersion: containerservice.azure.com/v1api20240402preview
      kind: ManagedCluster
      name: prd-aso-cluster
      namespace: default
  timeout: 30m
  retryInterval: 5m
  suspend: false