apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - high-performance/nodepool.yaml
  # - high-performance/policy.yaml
  - infrastructure/nodepool.yaml
  # - infrastructure/policy.yaml
  - tests/test-deployments.yaml