apiVersion: kubernetesconfiguration.azure.com/v1api20230501
kind: FluxConfiguration
metadata:
  name: aso-flux-config
  namespace: default
spec:
  azureName: aso-flux-config
  # Git repository configuration
  gitRepository:
    repositoryRef:
      branch: main
    url: https://github.com/davidmarkgardiner/aso-flux.git
    timeoutInSeconds: 60
    syncIntervalInSeconds: 120
  # Kustomization configurations
  kustomizations:
    apps:
      path: ./clusters/aks-secure
      dependsOn: ["base"]
      timeoutInSeconds: 600
      syncIntervalInSeconds: 120
      prune: true
      force: true
      wait: true  # Wait for reconciliation
    base:
      path: ./base
      dependsOn: []
      timeoutInSeconds: 300
      syncIntervalInSeconds: 60
      prune: true
      force: true
      wait: true
  # Installation namespace
  namespace: flux-system
  # Owner reference (required)
  owner:
    group: containerservice.azure.com
    kind: ManagedCluster
    name: aks-secure
  # Source configuration
  sourceKind: GitRepository
  scope: cluster
  # Reconciliation settings
  reconciliationWaitDuration: PT10M  # Wait up to 10 minutes for reconciliation
  waitForReconciliation: true  # Wait for kustomizations to reconcile
  # Optional: Suspend reconciliation if needed
  suspend: false
  # Optional: Protected settings (for sensitive data)
  configurationProtectedSettings:
    name: flux-git-credentials
    key: git-auth