apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: aso-base

commonLabels:
  app.kubernetes.io/part-of: aso-platform
  managed-by: flux

namePrefix: aso-

resources:
  - namespace.yaml
  - managed-cluster.yaml