apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: aso-ppe

namePrefix: ppe-
nameSuffix: ""

commonLabels:
  environment: ppe
  app.kubernetes.io/environment: ppe

resources:
  - ../../base

configMapGenerator:
  - name: cluster-variables
    namespace: default
    literals:
      - SUBSCRIPTION_ID=00000000-0000-0000-0000-000000000000
      - RESOURCE_GROUP=aks-ppe-rg
      - CLUSTER_NAME=aks-ppe
      - VNET_NAME=aks-ppe-vnet
      - SUBNET_NAME=aks-ppe-subnet
      - SERVICE_CIDR=10.42.0.0/16
      - DNS_SERVICE_IP=10.42.0.10
      - POD_CIDR=10.245.0.0/16
      - LOCATION=eastus
      - DNS_PREFIX=aks-ppe-dns
      - IDENTITY_NAME=aks-ppe-identity
      - ADMIN_GROUP_ID=00000000-0000-0000-0000-000000000000
      - SYSTEM_NODE_VM_SIZE=Standard_D4s_v3
      - ENVIRONMENT=ppe
      - PROJECT_NAME=aks-project
      - COST_CENTER=it-dept
      - SECURITY_LEVEL=elevated

patchesStrategicMerge:
  - cluster-patch.yaml

replacements:
  - source:
      kind: ConfigMap
      name: cluster-variables
      fieldPath: data.CLUSTER_NAME
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - metadata.name
  - source:
      kind: ConfigMap
      name: cluster-variables
      fieldPath: data.RESOURCE_GROUP
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.owner.name
  - source:
      kind: ConfigMap
      name: cluster-variables
      fieldPath: data.LOCATION
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.location
  - source:
      kind: ConfigMap
      name: cluster-variables
      fieldPath: data.DNS_PREFIX
    targets:
      - select:
          kind: ManagedCluster
        fieldPaths:
          - spec.dnsPrefix